// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: executor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExecutorServiceClient is the client API for ExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutorServiceClient interface {
	// / Processes a batch
	ProcessBatch(ctx context.Context, in *ProcessBatchRequest, opts ...grpc.CallOption) (*ProcessBatchResponse, error)
	ProcessBatchStream(ctx context.Context, opts ...grpc.CallOption) (ExecutorService_ProcessBatchStreamClient, error)
}

type executorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorServiceClient(cc grpc.ClientConnInterface) ExecutorServiceClient {
	return &executorServiceClient{cc}
}

func (c *executorServiceClient) ProcessBatch(ctx context.Context, in *ProcessBatchRequest, opts ...grpc.CallOption) (*ProcessBatchResponse, error) {
	out := new(ProcessBatchResponse)
	err := c.cc.Invoke(ctx, "/executor.v1.ExecutorService/ProcessBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) ProcessBatchStream(ctx context.Context, opts ...grpc.CallOption) (ExecutorService_ProcessBatchStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExecutorService_ServiceDesc.Streams[0], "/executor.v1.ExecutorService/ProcessBatchStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &executorServiceProcessBatchStreamClient{stream}
	return x, nil
}

type ExecutorService_ProcessBatchStreamClient interface {
	Send(*ProcessBatchRequest) error
	Recv() (*ProcessBatchResponse, error)
	grpc.ClientStream
}

type executorServiceProcessBatchStreamClient struct {
	grpc.ClientStream
}

func (x *executorServiceProcessBatchStreamClient) Send(m *ProcessBatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *executorServiceProcessBatchStreamClient) Recv() (*ProcessBatchResponse, error) {
	m := new(ProcessBatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExecutorServiceServer is the server API for ExecutorService service.
// All implementations must embed UnimplementedExecutorServiceServer
// for forward compatibility
type ExecutorServiceServer interface {
	// / Processes a batch
	ProcessBatch(context.Context, *ProcessBatchRequest) (*ProcessBatchResponse, error)
	ProcessBatchStream(ExecutorService_ProcessBatchStreamServer) error
	mustEmbedUnimplementedExecutorServiceServer()
}

// UnimplementedExecutorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExecutorServiceServer struct {
}

func (UnimplementedExecutorServiceServer) ProcessBatch(context.Context, *ProcessBatchRequest) (*ProcessBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedExecutorServiceServer) ProcessBatchStream(ExecutorService_ProcessBatchStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessBatchStream not implemented")
}
func (UnimplementedExecutorServiceServer) mustEmbedUnimplementedExecutorServiceServer() {}

// UnsafeExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServiceServer will
// result in compilation errors.
type UnsafeExecutorServiceServer interface {
	mustEmbedUnimplementedExecutorServiceServer()
}

func RegisterExecutorServiceServer(s grpc.ServiceRegistrar, srv ExecutorServiceServer) {
	s.RegisterService(&ExecutorService_ServiceDesc, srv)
}

func _ExecutorService_ProcessBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).ProcessBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executor.v1.ExecutorService/ProcessBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).ProcessBatch(ctx, req.(*ProcessBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_ProcessBatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutorServiceServer).ProcessBatchStream(&executorServiceProcessBatchStreamServer{stream})
}

type ExecutorService_ProcessBatchStreamServer interface {
	Send(*ProcessBatchResponse) error
	Recv() (*ProcessBatchRequest, error)
	grpc.ServerStream
}

type executorServiceProcessBatchStreamServer struct {
	grpc.ServerStream
}

func (x *executorServiceProcessBatchStreamServer) Send(m *ProcessBatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *executorServiceProcessBatchStreamServer) Recv() (*ProcessBatchRequest, error) {
	m := new(ProcessBatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExecutorService_ServiceDesc is the grpc.ServiceDesc for ExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "executor.v1.ExecutorService",
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessBatch",
			Handler:    _ExecutorService_ProcessBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessBatchStream",
			Handler:       _ExecutorService_ProcessBatchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "executor.proto",
}
